BUSCO module update

diff --git a/modules/nf-core/busco/busco/busco-busco.diff b/modules/nf-core/busco/busco/busco-busco.diff
--- a/modules/nf-core/busco/busco/busco-busco.diff
+++ b/modules/nf-core/busco/busco/busco-busco.diff
@@ -1,44 +1,43 @@
 Changes in component 'nf-core/busco/busco'
+'modules/nf-core/busco/busco/environment.yml' is unchanged
 'modules/nf-core/busco/busco/meta.yml' is unchanged
 Changes in 'busco/busco/main.nf':
 --- modules/nf-core/busco/busco/main.nf
 +++ modules/nf-core/busco/busco/main.nf
-@@ -22,19 +22,7 @@
-     val clean_intermediates
+@@ -1,6 +1,5 @@
+ process BUSCO_BUSCO {
+     tag "${meta.id}"
+-    label 'process_medium'
  
-     output:
--    tuple val(meta), path("*-busco.batch_summary.txt"), emit: batch_summary
--    tuple val(meta), path("short_summary.*.txt"), emit: short_summaries_txt, optional: true
--    tuple val(meta), path("short_summary.*.json"), emit: short_summaries_json, optional: true
--    tuple val(meta), path("*-busco.log"), emit: log, optional: true
--    tuple val(meta), path("*-busco/*/run_*/full_table.tsv"), emit: full_table, optional: true
--    tuple val(meta), path("*-busco/*/run_*/missing_busco_list.tsv"), emit: missing_busco_list, optional: true
--    tuple val(meta), path("*-busco/*/run_*/single_copy_proteins.faa"), emit: single_copy_proteins, optional: true
--    tuple val(meta), path("*-busco/*/run_*/busco_sequences"), emit: seq_dir, optional: true
--    tuple val(meta), path("*-busco/*/translated_proteins"), emit: translated_dir, optional: true
--    tuple val(meta), path("*-busco"), emit: busco_dir
--    tuple val(meta), path("busco_downloads/lineages/*"), emit: downloaded_lineages, optional: true
--    tuple val(meta), path("*-busco/*/run_*/busco_sequences/single_copy_busco_sequences/*.faa"), emit: single_copy_faa, optional: true
--    tuple val(meta), path("*-busco/*/run_*/busco_sequences/single_copy_busco_sequences/*.fna"), emit: single_copy_fna, optional: true
-+    tuple val(meta), path("*-busco/*/run_*"), emit: busco_dir
+     conda "${moduleDir}/environment.yml"
+     container "${workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container
+@@ -50,7 +49,7 @@
+     def busco_lineage = lineage in ['auto', 'auto_prok', 'auto_euk']
+         ? lineage.replaceFirst('auto', '--auto-lineage').replaceAll('_', '-')
+         : "--lineage_dataset ${lineage}"
+-    def busco_lineage_dir = busco_lineages_path ? "--download_path ${busco_lineages_path}" : ''
++    def busco_lineage_dir = busco_lineages_path ? "--download_path ${busco_lineages_path} --offline" : ''
+     def intermediate_files = [
+         './*-busco/*/auto_lineage',
+         './*-busco/*/**/{miniprot,hmmer,.bbtools}_output',
+@@ -111,8 +110,13 @@
  
-     path "versions.yml", emit: versions
- 
-@@ -105,11 +93,6 @@
-     # find and remove broken symlinks from the cleanup
-     find . -xtype l -delete
- 
--    # Move files to avoid staging/publishing issues
--    mv ${prefix}-busco/batch_summary.txt ${prefix}-busco.batch_summary.txt
--    mv ${prefix}-busco/*/short_summary.*.{json,txt} . || echo "Short summaries were not available: No genes were found."
--    mv ${prefix}-busco/logs/busco.log ${prefix}-busco.log
--
      if grep 'Run failed; check logs' ${prefix}-busco.batch_summary.txt > /dev/null
      then
-         echo "Busco run failed"
+-        echo "Busco run failed"
+-        exit 1
++        if grep -Fx 'Sequence too long (max 32000000 permitted).' ${prefix}-busco.log > /dev/null
++        then
++            echo "Prodigal can't run on this genome. Skipping it"
++        else
++            echo "Busco run failed"
++            exit 1
++        fi
+     fi
+     """
+ 
 
-'modules/nf-core/busco/busco/environment.yml' is unchanged
-'modules/nf-core/busco/busco/tests/main.nf.test' is unchanged
-'modules/nf-core/busco/busco/tests/nextflow.config' is unchanged
 'modules/nf-core/busco/busco/tests/main.nf.test.snap' is unchanged
+'modules/nf-core/busco/busco/tests/nextflow.config' is unchanged
+'modules/nf-core/busco/busco/tests/main.nf.test' is unchanged
 ************************************************************
